{
    "int": ${int:0,1},
    "int": ${int:0,10},
    "int_min_max": ${int:-100,100},
    "float": ${float:0,1},
    "float_rounded": ${float:-100,100},
    "name::full": "${<1>name::full}",
    "name::first": "${<1>name::first}",
    "name::last": "${<1>name::last}",
    "place": "${<1>location::place}",
    "address": "${<1>location::address}",
    "street": "${<1>location::street}",
    "guid": "${guid}",
    "phone": "${<1>phone}",
    "phone::mobile": "${<1>phone::mobile}",
    "phone::landline": "${<1>phone::landline}",
    "set": "${set:First,Second,Third}",
    "dist::normal": ${dist::normal:0,1},
    "dist::normal<1>": ${<1>dist::normal:0,1},
    "dist::normal<1>": ${<1>dist::normal:0,1},
    "error": "${unsupported}",
    "error_invalid_args": ${float:1}
}